name: device_simulator
description: DeviceSimulator allows you to easily test your Flutter app for different screen resolutions and platforms.
version: 0.9.6
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: https://github.com/vlidholt/device_simulator

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_navigator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  assets:
    - ios-bar-black.png
    - ios-bar-white.png
  fonts:
    - family: appleicon
      fonts:
        - asset: assets/appleicon.ttf
